### ISSUE TITLE
Data Preparation

### ISSUE THREAD

**Issue by anggapark** [HijazP/c23-pe02#18]
Periksa apakah dataset yang diberikan dalam format yang diinginkan seperti csv, excel, atau json.
Pastikan semua feature yang dibutuhkan ada pada dataset

- status: dimulai setelah mendapat dataset dari stakeholder

**Comment by rafzarf** [comment]
Setelah berdiskusi dengan Kak Henokh, saya dan @anggapark mencoba membuat dataset:

**1. Dataset Course** (https://docs.google.com/spreadsheets/d/1i9_01se2A_FvatS0Byn47SoiHbwXNr1zt_rZhsADhZM/edit?usp=share_link)

Features: 
- courseID 
- judul 
- deskripsi 
- dampak 
- modul


**2. Dataset Problem Desa** (https://docs.google.com/spreadsheets/d/13aNQLy-DnUqiw6K2eHA0YlFIxH8V9IKOC4TfOELrQdw/edit?usp=share_link)

Features: 
- desa 
- problem 
- lokasi 
- jenis_masalah

**Comment by HijazP** [comment]
Sudah oke, lanjut ke praproses data
