### ISSUE TITLE
API problem desa

### ISSUE THREAD

**Issue by HijazP** [HijazP/c23-pe02#40]
- GET masalah desa berdasarkan session login (email yang login) -> ngelist semua masalah desa dari database sesuai desanya
- POST masalah desa (judul problem, deskripsi)
- DELETE masalah desa
- PUT masalah desa

**Comment by novans123** [comment]
yang GET masalah desa dari login email gimana ya maksudnya? nangkep dari email user yg baru login kah?

**Comment by HijazP** [comment]
bukan, ya nampilin problem desa doang sih tapi yang terkait akunnya

**Comment by MuhammadAbiyyuFarhan** [comment]
put masalah desa tuh apa yak

**Comment by MuhammadAbiyyuFarhan** [comment]
![Image](https://github.com/HijazP/c23-pe02/assets/128464185/989ef18a-86c2-478a-9fb6-33cfdf41ca9b)

gw gabut hari ini,nyobain bikin baru get, post, delete. kaga ngerti maksudnya itu put apa

**Comment by novans123** [comment]
kayak buat ubah/edit judul/deskripsi mungkin

**Comment by MuhammadAbiyyuFarhan** [comment]
wokee

**Comment by 007Kohaku** [comment]
![Image](https://github.com/HijazP/c23-pe02/assets/113377534/0f1bf98d-12ff-479c-8173-5eb680945201)

gw udh jdi sihh ini harusnya, tpi coba ntar kita diskusiin lg, takutnya ada yg salah jg

**Comment by MuhammadAbiyyuFarhan** [comment]
mantep, task nya bisa di pindahin ke done aja kalo gitu

**Comment by HijazP** [comment]
review dulu

**Comment by MuhammadAbiyyuFarhan** [comment]
oh iya bener

**Comment by MuhammadAbiyyuFarhan** [comment]
https://drive.google.com/file/d/1gMBAM7Q8uc-My6_GAdxDApzNLoRHdNTN/view?usp=sharing

gw juga gabut bikin tadi, buat backup aja

**Comment by 007Kohaku** [comment]
@MuhammadAbiyyuFarhan pke nama desa juga? bukannya cuman masalah sama deskripsi doang? apa gmn? @HijazP

**Comment by HijazP** [comment]
ga perlu sih, kalo dari database, udah ada iddesa yang jadi foreign key

**Comment by MuhammadAbiyyuFarhan** [comment]
iya itu tadi gw tambahin aja soalnya gw bingung sendiri kalo gaada nama desanya

**Comment by novans123** [comment]
udah aman kah? atau ada yg krg
